# Generated by Django 3.0.4 on 2020-05-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adderss',
            new_name='address',
        ),
    ]
