# Generated by Django 3.0.4 on 2020-05-12 01:05

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to=accounts.models.user_directory_path),
        ),
    ]
