# Generated by Django 3.0.4 on 2020-05-12 22:00

import accounts.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200512_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
