# Generated by Django 3.0.4 on 2020-04-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinsta', '0006_auto_20200405_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
