# Generated by Django 3.0.4 on 2020-04-05 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinsta', '0008_auto_20200405_0111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
