# Generated by Django 3.0.4 on 2020-05-07 23:43

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myinsta', '0015_auto_20200507_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='photo/'),
        ),
    ]
