# Generated by Django 3.0.4 on 2020-05-08 00:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myinsta', '0020_auto_20200508_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='myinsta/photo'),
        ),
    ]
