# Generated by Django 3.0.4 on 2020-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinsta', '0024_post_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment_to_comment',
            name='user_id',
            field=models.TextField(blank=True),
        ),
    ]
